### ISSUE TITLE
Issues on variable statuses

### ISSUE THREAD

**Issue by mapgccv** [ampl/api-test#2]
Some tests (e.g. VariableTest.testSStatus, VariableTest.testStatus) fail with trace:
org.junit.ComparisonFailure: expected:<[low]> but was:<[bas]>
using CBC. Switching solver fixes the problem.

**Comment by vitaut** [comment]
Fixed, thanks.

**Comment by mapgccv** [comment]
More tests have the same problem:
ConstraintTest: testSStatus, testStatus
VariableInstanceTest: (same names)

and similarly, ObjectiveInstanceTest.testMessage and ObjectiveTest.TestMessage expect "optimal solution found" whilst CBC returns a string like:
CBC 2.8.8 optimal, objective 0

Also the test testSolverOutputSentToHandler fails as CBC returns something very strangeto AMPL in block mode:
24 solve_output
CBC 2.8.8: 24 solve_output
51 solve
CBC 2.8.8 optimal, objective -5
0 iterations
14 prompt1

**Comment by vitaut** [comment]
Fixed all except the last issue in https://github.com/ampl/api-test/commit/8696a8d0860cf313fc94412d99a506106719d21f. If you can reproduce the issue with the AMPL block output outside of the API, perhaps it's worth sending it to David.

**Comment by mapgccv** [comment]
Thanks for fixing these; the last item was indeed obtained outside the API, so I'm sending it to David.
